### ISSUE TITLE
Database Update Questions

### ISSUE THREAD

**Issue by clairehubel** [theunitedeffort/theunitedeffort.org#75]
Hi @trevorshannon @philhawksworth....Not sure if Github is the correct place for these comments, but anyway....

1. Let's make sure to launch on Sunday to avoid any updates being made to the SQL db, which would be very problematic for so many reasons. Phil and I can chat tomorrow in our meeting about the absolute minimum necessities for this to be OK. 

2. Let's teach either/both  Wei/Poul Erik how to make upcoming updates in the Airtable db. Their attention to detail and knowledge of the housing sites makes them ideal candidates for this. Ideally this would happen in time for them to do this update at the end of May, transitioning to them doing it moving forward, and then training a volunteer to do so. I suggest: 

- One of them does discovery of needed updates, in whatever way they generally do this
- Trevor oversees them updating the Airtable db
- June's update happens with Wei/Poul Erik in charge, with Trevor in a consultant role
- July: Wei/Poul Erik train replacements for themselves, or others to help with this. If they prefer to retain ownership of this, then that is fine, so long as Trevor is not in charge of this.

Sound good?

**Comment by trevorshannon** [comment]
That sounds perfect.  The latest db import did hit some snags.  Still
aiming for launch end of day Sunday, but it could be tight.  Most of my
remaining tasks are pending the final db import.

We can definitely get it done before the scheduled monthly database update.

I like the plan about training database updators.

**Comment by philhawksworth** [comment]
Yeah this sounds great.

Apologies that re-importing the data wasn't as smooth as it could have been. Since we've been iterating, the shape of the data is no longer quite the same in the 2 databases so I made some mistakes which luckily @trevorshannon spotted. I've set some time aside this morning to mop this up (I think I've got it now). 

I should have you unblocked by the time your day starts, @trevorshannon :)

I also have the weekend set aside to work on any other items required for the launch. I'd make the case that the site is already more valuable and complete that the existing one, and that we should launch. But let's work through our burndown list of items on the 2.0 Milestone as planned

**Comment by trevorshannon** [comment]
Sounds great!  Off to bed for me 😄 

agree that the site is already better than the current site; good to keep that perspective.

**Comment by clairehubel** [comment]
Thank you @philhawksworth !

**Comment by clairehubel** [comment]
I think so long as we launch before there is any threat of the SCL db being updated that’s the most important thing. If it’s not the 15th its OK. We just need to communicate this with Wei etc




Claire Hubel
she/her/hers
The United Effort Organization, Inc.
cell: 650-906-3158
